---
booktitle: Proceedings of Fifth European Conference on Algorithmic Fairness
shortname: ECAF
sections:
- name: Preface
  title: Preface
- name: Full paper
  title: Full Papers
- name: Extended abstract
  title: Extended Abstracts
volume: '350'
year: '2026'
start: 2026-09-02
end: 2026-09-04
published: 2026-09-30
conference_number: '5'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ECAF-2026
month: 0
cycles: false
bibtex_editor: De Bie, Tijl and Defrance, MaryBeth and Calders, Toon and Nguyen, Dennis
editor:
- given: Tijl
  family: De Bie
- given: MaryBeth
  family: Defrance
- given: Toon
  family: Calders
- given: Dennis
  family: Nguyen
title: Proceedings of Machine Learning Research
description: |
  Proceedings of Fifth European Conference on Algorithmic Fairness
    Held in Ghent University, Ghent, Belgium on 02-04 September 2026

  Published as Volume 350 by the Proceedings of Machine Learning Research on 30 September 2026.

  Volume Edited by:
    Tijl De Bie
    MaryBeth Defrance
    Toon Calders
    Dennis Nguyen

  Series Editors:
    Tegan Emerson
    Hoel Kervadec
    Neil D. Lawrence
date_str: 02--04 Sep
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v350"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v350
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v350
email: ''
conference:
  name: European Conference on Algorithmic Fairness
  url: https://2026.ecafconference.org/
  location: Ghent University, Ghent, Belgium
  dates:
  - 2026-09-02
  - 2026-09-03
  - 2026-09-04
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: ecaf26_clean.bib
# Site settings
# Original source:  ecaf26_clean.bib
